### PR TITLE
feat: add deriveLoading RxJs-Operator

### PR DESCRIPTION
**Pull request by mikelgo**
This PR will add a `deriveLoading` RxJs Operator which will emit a loading state/ boolean flag based on some underlying async operation. This will also be done in a "non-flickering" way.

I'm not sure where I can add some documentation for this. 

Looking forward to your feedback, probably also we can find a better name. I'm not completely happy.

### CODE REVIEW

**Comment by ajitzero** [comment]
Hi @mikelgo - Could you please [raise an issue](https://github.com/ngxtension/ngxtension-platform/issues/new) with details for the use case and a brief example of how to use it? This initially looked similar to #56 & #354, but the tests helped clarify things.

**Comment by mikelgo** [comment]
> Hi @mikelgo - Could you please [raise an issue](https://github.com/ngxtension/ngxtension-platform/issues/new) with details for the use case and a brief example of how to use it? This initially looked similar to #56 & #354, but the tests helped clarify things.

Issue created: https://github.com/ngxtension/ngxtension-platform/issues/440

**Comment by mikelgo** [comment]
Let me know if I need to do anything. I saw that CI was failing (however not sure why). 
build, test and lint for the new feature works on my local.

**Review by nartc — APPROVED** [review]

**Comment by hoc081098** [comment]
Nice 😂

**Pull request merged**
