### PR TITLE
Docs/create injectable es translation

### PR DESCRIPTION
**Pull request by sergidt**
create injectable spanish translation

### CODE REVIEW

**Comment by nartc** [comment]
Thank you for your contribution. Can you remove the package-lock.json since we're not using `npm`

**Comment by sergidt** [comment]
Done! :)

**Comment by sergidt** [comment]
After this PR, my intention is translate every pending page and, if you need to review some of them, as I said, I am a native Spanish speaker. ;) @nartc @eneajaho

**Comment by sergidt** [comment]
Is there any pending thing to be changed, from my side?

**Comment by sergidt** [comment]
I supose is not a good pr, waiting for a long time...

**Comment by eneajaho** [comment]
Hello @sergidt 
Sorry for taking this long 🙏 
I removed the package-lock.json and I'm merging this now.

**Review by eneajaho — APPROVED** [review]

**Comment by sergidt** [comment]
Ok, no worries, if you want I will proceed to translate others. Thanks @eneajaho

**Pull request merged**
