### PR TITLE
fix: reintroduce computedAsync which reexports and shows a deprecatio…

### PR DESCRIPTION
**Pull request by eneajaho**
…n notice

We need to release this in a patch I guess. And then I will remove it using the Breaking Changes flag and we can release a major.

### CODE REVIEW

**Comment by eneajaho** [comment]
> Thanks!
> 
> Btw @eneajaho, when i updated to 2.3 this popped up: `An unhandled exception occurred: Schematic "rename-computed" is missing a factory.`

Are you inside nx monorepo or normal angular app?

**Comment by Sergiobop** [comment]
> > Thanks!
> > Btw @eneajaho, when i updated to 2.3 this popped up: `An unhandled exception occurred: Schematic "rename-computed" is missing a factory.`
> 
> Are you inside nx monorepo or normal angular app?

Normal app:

```
Angular CLI: 17.3.5
Node: 20.11.0
Package Manager: npm 10.5.2
OS: darwin x64

Angular: 17.3.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

**Comment by eneajaho** [comment]
> > > Thanks!
> > > Btw @eneajaho, when i updated to 2.3 this popped up: `An unhandled exception occurred: Schematic "rename-computed" is missing a factory.`
> > 
> > 
> > Are you inside nx monorepo or normal angular app?
> 
> Normal app:
> 
> ```
> Angular CLI: 17.3.5
> Node: 20.11.0
> Package Manager: npm 10.5.2
> OS: darwin x64
> 
> Angular: 17.3.5
> ... animations, cdk, cli, common, compiler, compiler-cli, core
> ... forms, material, material-moment-adapter, platform-browser
> ... platform-browser-dynamic, router, service-worker
> ... youtube-player
> 
> Package                         Version
> ---------------------------------------------------------
> @angular-devkit/architect       0.1703.5
> @angular-devkit/build-angular   17.3.5
> @angular-devkit/core            17.3.5
> @angular-devkit/schematics      17.3.5
> @schematics/angular             17.3.5
> rxjs                            7.8.1
> typescript                      5.4.5
> zone.js                         0.14.4
> ```

This PR https://github.com/ngxtension/ngxtension-platform/pull/345 should solve the issue  🙌

**Comment by Sergiobop** [comment]
You are the best @eneajaho

Thanks

**Review by nartc — APPROVED** [review]

**Pull request merged**
